import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Routes, Route, useLocation } from 'react-router-dom';
import './styles.css';
import './navbar.css';
import './brand.css';
import ksliLogo from './assets/branding/ksli-logo.png';
import ceewLogo from '../assets/CEEW.png';
import earthonomicLogo from '../assets/Earthonomic Engineers.png';
import salzerLogo from '../assets/Salzer.png';
import schneiderLogo from '../assets/Schneider Electric.png';
import sierraLogo from '../assets/Sierra.png';
import edfLogo from '../assets/Environmental Defense Fund.png';
import kisanLogo from '../assets/Kisan Konnect.png';
import mobitechLogo from '../assets/Mobitech Wireless Solutions.png';
import nddbLogo from '../assets/NDDB Mrida Limited.png';
import csaLogo from '../assets/Centre for Sustainable Agriculture.png';
import bnhsLogo from '../assets/BNHS India.png';
import naturalistLogo from '../assets/The Naturalist School.png';
import zooOutreachLogo from '../assets/Zoo Outreach Organisation.png';
import aTreeLogo from '../assets/a tree.png';
import wwfLogo from '../assets/WWF.png';
import igbcLogo from '../assets/IGBC.png';
import nicmarLogo from '../assets/NICMAR.png';
import aurovilleLogo from '../assets/Auroville Botanical Gardens.png';
import udriLogo from '../assets/Urban Design Research Institute.png';
import biomeLogo from '../assets/Biome Environmental.png';
import thannalLogo from '../assets/thannal.png';
import AboutKSLI from './pages/AboutKSLI.jsx';

const img = {
  hero: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcrwWa2o5nAozqqQvUmytqo_H5g2TNutO1HQaexxVhNVGMzd3EHQZtW5NrJ4Cau1x28EfnmfV7FLRNk_crjxfahtdYIl39mroK_JR1pn-2xZtPD8Q5o8RzXmyu6SuAx0dhw0Yl8nVgSXWreMpqyX_b77lBnQvpjfmG6KyVtScBb_v3DpyQjGkP0CIjm1sZeLkJKX-5Oy6ibBeWkEKIOk8iga-55mgEpkqn4m3Ay4DVhgnYc2cZNOQ0Vw',
  sustainability: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0aCfPGhwkzRiq7INx_Ku7YGgODgysXSucL-W3k7qk9eu_kloM62NV55XdkMPM0iL8AiD-CZLk_R24QathZPnOboweQPs-OYzDuOp0l9-TaiwqFTJKMS2h9DdlHpaobN9gkQ6WLpG0HmdDLV_ugP2Fx9hk1fttB50b3nebFXo0gBwsLpLN9GHLlFRXS9AkjOpa301BU1QPfYRc2zBCqvfYxUaZNh61mmit4jwdRxqzoOvPsfDmbToulw',
  pathway: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAltNZbzl24YOhTpyttO8MN3RtWjYr-alPnC9UZze6fpMLYgP7ErFYMDI02fNXQqeuuO2J_7fuc4cHqS7AoFxoMawEioD_qgxCw-QrED4P2FZfSrejylmvv3IwZy2qHGmLApJK8CRPO6vzjSlD3eS0ZZphrqUUfnqa7bRCn0KMJPT_42IeDN0Izvr4d00FaRlu6bFwiB9jtFPrqdV3oxLMxyRXh7zpQeMevtVjKc9-gbxBa9tUViiG0aQ'
};
const navItems = [
  { label: 'Home', to: '/', exact: true },
  { label: 'About KSLI', to: '/about' },
  { label: 'Sustainability', to: '/sustainability', items: [['Overview','/sustainability'],['Kumaraguru Microcosm','/sustainability/microcosm'],['Research','/sustainability/research'],['Projects','/sustainability/projects'],['Events','/sustainability/events']] },
  { label: 'Livelihood', to: '/livelihood', items: [['Overview','/livelihood'],['Research','/livelihood/research'],['Projects','/livelihood/projects'],['Events','/livelihood/events']] },
  { label: 'Academic Programs', to: '/academic-programs' },
  { label: 'Contact', to: '/contact' }
];
function Header(){ const [open,setOpen]=useState(null); const [mobile,setMobile]=useState(false); const [scrolled,setScrolled]=useState(false); const loc=useLocation(); const close=()=>{setOpen(null);setMobile(false)}; React.useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>50); window.addEventListener('scroll',onScroll); return ()=>window.removeEventListener('scroll',onScroll);},[]); return <header className={`site-header ${scrolled?'scrolled':''}`}><nav className="nav shell"><Link className="brand" to="/" onClick={close} aria-label="Kumaraguru Sustainability and Livelihood Institute home"><img src={ksliLogo} alt="Kumaraguru Sustainability and Livelihood Institute" width="275" height="52" /></Link><button className="menu-button" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}>☰</button><div className={`nav-links ${mobile?'show':''}`}>
{navItems.map((item,i)=>item.items?<div className="nav-group" key={item.label}><button onClick={()=>setOpen(open===i?null:i)} className={loc.pathname.startsWith(item.to)?'active':''}>{item.label}<b>⌄</b></button><div className={`dropdown ${open===i?'open':''}`}>{item.items.map(([label,to])=><Link to={to} onClick={close} key={to}>{label}</Link>)}</div></div>:<NavLink to={item.to} end={item.exact} onClick={close} key={item.label}>{item.label}</NavLink>)}<Link className="submit-button mobile-submit" to="/submit-a-project" onClick={close}>Submit a Project</Link></div><Link className="submit-button desktop-submit" to="/submit-a-project">Submit a Project ↗</Link></nav></header> }
function Footer(){return <footer className="footer"><div className="shell footer-grid"><div><Link className="brand inverse" to="/">KSLI</Link><p>© 2026 Kumaraguru Sustainability and Livelihood Institute.</p></div><div><p className="eyebrow">Explore</p><Link to="/sustainability">Sustainability</Link><Link to="/livelihood">Livelihood</Link><Link to="/academic-programs">Academic Programs</Link></div><div><p className="eyebrow">Connect</p><Link to="/coe-partners">CoE & Partners</Link><div style={{display:'grid',gap:'8px',paddingLeft:'12px',opacity:0.8,fontSize:'12px'}}><Link to="/coe-partners/centres-of-excellence">CoE - Dairy</Link><Link to="/coe-partners/centres-of-excellence">CoE - Sugarcane</Link><Link to="/coe-partners/centres-of-excellence">CoE - Social Development</Link></div><Link to="/about">About KSLI</Link><Link to="/contact">Contact</Link></div></div></footer>}
function Layout({children}){return <><Header/><main>{children}</main><Footer/></>}
function SectionHeading({eyebrow, title, children, center=false}){return <div className={`section-heading ${center?'center':''}`}>{eyebrow&&<p className="eyebrow teal">{eyebrow}</p>}<h2>{title}</h2>{children&&<p>{children}</p>}</div>}
function CountUpStat({ number, label, icon }) { const [count, setCount] = useState(0); const [inView, setInView] = useState(false); const ref = React.useRef(); React.useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setInView(true); observer.disconnect(); } }, { threshold: 0.1 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); React.useEffect(() => { if (!inView) return; const target = parseInt(number.replace(/\D/g, '')); if (!target) return; let startTimestamp = null; const duration = 1500; const step = (timestamp) => { if (!startTimestamp) startTimestamp = timestamp; const progress = Math.min((timestamp - startTimestamp) / duration, 1); const easeOut = progress === 1 ? 1 : 1 - Math.pow(2, -10 * progress); setCount(Math.floor(easeOut * target)); if (progress < 1) { window.requestAnimationFrame(step); } }; window.requestAnimationFrame(step); }, [inView, number]); const displayValue = parseInt(number.replace(/\D/g, '')) ? `${count}${number.replace(/[0-9]/g, '')}` : number; return <div ref={ref} className={`stat ${inView ? 'animate' : ''}`}><span>{icon}</span><strong>{displayValue}</strong><small>{label}</small></div>; }
function Stats(){return <section className="stats"><div className="shell stats-grid">{[['⌁','5k+','Farmers Engaged'],['♧','₹5Cr+','Adaptation Grant'],['⌘','3','Centres of Excellence'],['◈','20+','Partner Organizations']].map(([i,n,l])=><CountUpStat key={l} icon={i} number={n} label={l} />)}</div></section>}
function EntryCard({title, type='RESEARCH', text='Content details will be added in a future update.', image}){return <article className="entry-card">{image?<img src={image} alt=""/>:<div className="card-art"/>}<div className="card-copy"><p className="eyebrow teal">{type}</p><h3>{title}</h3><p>{text}</p><button className="text-link">Explore <span>→</span></button></div></article>}
function CtaCard({title,text,to,image}){return <Link to={to} className="cta-card" style={{backgroundImage:`linear-gradient(0deg,rgba(27,40,64,.94),rgba(27,40,64,.16)),url(${image})`}}><span className="cta-icon">⌁</span><h3>{title}</h3><p>{text}</p><strong>Explore domain →</strong></Link>}
function FocusGrid({areas}){return <div className="focus-grid">{areas.map((a,i)=><article className="focus-card" key={a}><span>0{i+1}</span><h3>{a}</h3><p>Programme details and related activity will be featured here.</p></article>)}</div>}
function GroupedList({groups}){return <div className="grouped-list">{groups.map(g=><section key={g.title}><h3>{g.title}</h3>{g.items.map(item=><div className="list-item" key={item}><span>↗</span>{item}</div>)}</section>)}</div>}
function Timeline(){return <div className="timeline">{['Foundational Course','Systems Thinking','Practical Prototyping','Capstone Project'].map((x,i)=><div className="timeline-step" key={x}><span>{i+1}</span><div><h3>{x}</h3><p>Structured learning milestone; full programme content is forthcoming.</p></div></div>)}</div>}
function LogoGrid({title='Our Partners', categories}){
  if (categories) {
    return <section><SectionHeading title={title}/><div style={{display:'flex',flexDirection:'column',gap:'40px'}}>{categories.map(cat=><div key={cat.name}><h3 style={{marginBottom:'16px',color:'var(--teal)',fontSize:'14px',fontWeight:'600',textTransform:'uppercase',letterSpacing:'0.05em'}}>{cat.name}</h3><div className="marquee-container"><div className="marquee-track"><div className="marquee-group">{cat.partners.map(p=><div className="logo-tile" style={{padding:'0 12px', fontSize:'13px', fontWeight:'500', minHeight:'80px', minWidth:'180px', display:'flex', alignItems:'center', justifyContent:'center', textAlign:'center', border:'0'}} key={p.name || p}>{p.logo ? <img src={p.logo} alt={p.name} style={{maxHeight:'60px', maxWidth:'100%', objectFit:'contain'}} /> : (p.name || p)}</div>)}</div><div className="marquee-group" aria-hidden="true">{cat.partners.map(p=><div className="logo-tile" style={{padding:'0 12px', fontSize:'13px', fontWeight:'500', minHeight:'80px', minWidth:'180px', display:'flex', alignItems:'center', justifyContent:'center', textAlign:'center', border:'0'}} key={(p.name || p)+'-dup'}>{p.logo ? <img src={p.logo} alt={p.name} style={{maxHeight:'60px', maxWidth:'100%', objectFit:'contain'}} /> : (p.name || p)}</div>)}</div></div></div></div>)}</div></section>;
  }
  const names=['CEEW','Schneider Electric','Sierra','Earthonomic Engineers','Salzer','Environmental Defense Fund','Kisan Konnect','Mobitech Wireless'];
  return <section><SectionHeading title={title}/><div className="marquee-container"><div className="marquee-track"><div className="marquee-group">{names.map((name,i)=><div className="logo-tile" style={{padding:'0 10px', fontSize:'12px', minWidth:'180px'}} key={name}><span>{String(i+1).padStart(2,'0')}</span>{name}</div>)}</div><div className="marquee-group" aria-hidden="true">{names.map((name,i)=><div className="logo-tile" style={{padding:'0 10px', fontSize:'12px', minWidth:'180px'}} key={name+'-dup'}><span>{String(i+1).padStart(2,'0')}</span>{name}</div>)}</div></div></div></section>;
}
function AnimatedSectionHeading({eyebrow, title, children}){const [inView, setInView] = useState(false); const ref = React.useRef(); React.useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setInView(true); observer.disconnect(); } }, { threshold: 0.2 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref} className={`section-heading center core-purpose-animated ${inView ? 'in-view' : ''}`}>{eyebrow&&<p className="eyebrow teal">{eyebrow}</p>}<h2>{title}</h2>{children&&<p>{children}</p>}</div>}
function Home(){
  const partnerCategories = [
    { name: 'Resource Efficiency', partners: [{name:'CEEW', logo:ceewLogo}, {name:'Schneider Electric', logo:schneiderLogo}, {name:'Sierra', logo:sierraLogo}, {name:'Earthonomic Engineers', logo:earthonomicLogo}, {name:'Salzer', logo:salzerLogo}] },
    { name: 'Sustainable Agriculture', partners: [{name:'Environmental Defense Fund', logo:edfLogo}, {name:'Kisan Konnect', logo:kisanLogo}, {name:'Mobitech Wireless Solutions', logo:mobitechLogo}, {name:'NDDB Mrida Limited', logo:nddbLogo}, {name:'Centre for Sustainable Agriculture', logo:csaLogo}] },
    { name: 'Nature Conservation', partners: [{name:'BNHS India', logo:bnhsLogo}, {name:'The Naturalist School', logo:naturalistLogo}, {name:'Zoo Outreach Organisation', logo:zooOutreachLogo}, {name:'a tree', logo:aTreeLogo}, {name:'WWF', logo:wwfLogo}] },
    { name: 'Green Buildings', partners: [{name:'IGBC', logo:igbcLogo}, {name:'NICMAR', logo:nicmarLogo}, {name:'Auroville Botanical Gardens', logo:aurovilleLogo}, {name:'Urban Design Research Institute', logo:udriLogo}, {name:'Biome Environmental', logo:biomeLogo}, {name:'thannal', logo:thannalLogo}] }
  ];
  return <><section className="home-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(27,40,64,.96),rgba(27,40,64,.74),transparent),url(${img.hero})`}}><div className="shell"><p className="teal intro-label">Kumaraguru Sustainability and Livelihood Institute</p><h1>Fostering a Sustainable Future through Knowledge and Action</h1><p>Advancing sustainability and livelihoods through research, education, entrepreneurship, and community transformation.</p><div className="actions"><Link className="primary" to="/academic-programs">Explore Programs →</Link><Link className="secondary" to="/coe-partners">Partner With Us</Link></div></div></section><Stats/><section className="section narrow center"><AnimatedSectionHeading eyebrow="Our Core Purpose" title="KSLI is proposed as a strategic institutional platform to consolidate, lead, and scale sustainability- and livelihood-focused initiatives, aligning academic programs, research, partnerships, flagship events, and community engagement under a single governance and identity."/></section><section className="section muted"><div className="shell cards-2"><CtaCard title="Sustainability Initiatives" text="Advancing resource efficiency, sustainable agriculture, nature conservation, and sustainable human settlements through applied research and green infrastructure." to="/sustainability" image={img.sustainability}/><CtaCard title="Livelihood Development" text="Strengthening farm-based, off-farm, and non-farm livelihoods through capacity building, entrepreneurship, and market linkages." to="/livelihood" image={img.pathway}/></div></section><section className="section shell"><SectionHeading title="Latest Updates">Recent flagship events and initiatives.</SectionHeading><div className="entry-grid"><EntryCard title="Dairy Yatra" type="SUSTAINABILITY EVENT"/><EntryCard title="Student Conclave for Climate Action" type="SUSTAINABILITY EVENT"/><EntryCard title="Young Farmers Conclave" type="LIVELIHOOD EVENT"/></div></section><section className="section muted"><SectionHeading title="Academic Programs" center={true}/><div className="shell entry-grid"><EntryCard title="MBA – Agri Business Management" type="ACADEMIC PROGRAM"/><EntryCard title="MBA – Sustainability Management" type="ACADEMIC PROGRAM"/><EntryCard title="MSW – Master of Social Work" type="ACADEMIC PROGRAM"/></div></section><section className="section shell"><div className="shell"><LogoGrid title="Our Collaborators" categories={partnerCategories}/></div></section><section className="bottom-cta"><div className="shell"><div><p className="eyebrow teal">Collaborate with KSLI</p><h2>Have a project that can create meaningful impact?</h2></div><Link className="primary" to="/submit-a-project">Submit a Project →</Link></div></section></>}
function DomainOverview({domain}){const sustain=domain==='Sustainability'; const areas=sustain?['Circular Economy','Climate Action','Water Stewardship','Renewable Energy','Biodiversity Conservation','Sustainable Agriculture']:['Community Enterprise','Skills & Learning','Inclusive Innovation','Rural Futures','Social Impact','Local Economies'];return <><section className={`domain-hero ${sustain?'sustain':''}`} style={sustain?{backgroundImage:`linear-gradient(90deg,#1b2840ee,#1b2840c0),url(${img.sustainability})`}:{}}><div className="shell"><p className="eyebrow teal">KSLI Domain</p><h1>{sustain?'Sustainability at KSLI':'Livelihood at KSLI'}</h1><p>{sustain?'Environmental stewardship is central to KSLI’s institutional work.':'KSLI enables sustainable livelihoods through research, learning and community partnership.'}</p></div></section><section className="section shell"><SectionHeading eyebrow="Areas of work" title={sustain?'Core Focus Areas':'Livelihood Focus Areas'}/><FocusGrid areas={areas}/></section></>}
function Microcosm(){return <><PageIntro eyebrow="Sustainability" title="Kumaraguru Microcosm">A living campus laboratory that brings sustainability principles into everyday practice.</PageIntro><section className="section shell"><SectionHeading title="Campus Focus Areas"/><FocusGrid areas={['Campus Biodiversity','Waste Management','Water Stewardship','Energy Conservation']}/></section><section className="section muted"><div className="shell"><SectionHeading title="Microcosm Resources"/><GroupedList groups={[{title:'Awards & Recognition',items:['Recognition and awards placeholder']},{title:'Policies',items:['Campus sustainability policy placeholder']},{title:'Reports & Documents',items:['Downloadable reports placeholder']} ]}/></div></section></>}
function Listing({domain='Sustainability', kind='Research'}){const names=kind==='Research'?['Systems research initiative','Community knowledge project','Applied research programme']:kind==='Projects'?['Campus impact initiative','Collaborative field project','Sustainable systems project']:['Annual institute gathering','Knowledge exchange session','Community engagement event'];return <><PageIntro eyebrow={domain} title={`${domain} ${kind}`}>Featured {kind.toLowerCase()} entries will be listed here.</PageIntro><section className="section shell"><div className="entry-grid">{names.map((x,i)=><EntryCard key={x} title={x} type={kind.slice(0,-1).toUpperCase()} image={i===0?img.sustainability:null}/>)}</div></section></>}
function AcademicOverview(){return <><PageIntro eyebrow="Learning at KSLI" title="Academic Programs">Structured opportunities that connect academic knowledge with responsible practice.</PageIntro><section className="section shell"><FocusGrid areas={['Degrees','Sustainability Pathway','Prototyping','Certificates']}/></section></>}
function Programs({type}){if(type==='pathway')return <><PageIntro title="Sustainability Pathway">A journey from foundation to action-oriented learning.</PageIntro><section className="section shell two-column"><div className="image-panel" style={{backgroundImage:`url(${img.pathway})`}}/><div><SectionHeading title="Academic Roadmap"/><Timeline/></div></section></>; const map={degrees:['Graduate Program Placeholder','Research Degree Placeholder'],prototyping:['Applied Prototyping','Practice-Based Learning'],certificates:['Foundation Certificates','Professional Certificates']};return <><PageIntro title={type==='degrees'?'Degrees':type==='prototyping'?'Prototyping':'Certificates'}>Programme content will be curated and published separately.</PageIntro><section className="section shell">{type==='certificates'?<GroupedList groups={map.certificates.map(x=>({title:x,items:['Programme placeholder','Programme placeholder']}))}/>:<div className="entry-grid">{map[type].map(x=><EntryCard key={x} title={x} type="ACADEMIC PROGRAM"/>)}</div>}</section></>}
function Partners({centres=false}){return <><PageIntro eyebrow="Collaboration" title={centres?'Centres of Excellence':'CoE & Partners'}>Working with institutions, communities and industry to advance shared goals.</PageIntro><section className="section shell">{centres?<div className="entry-grid">{['Centre for Sustainable Systems','Centre for Community Innovation','Centre for Applied Learning'].map(x=><EntryCard key={x} title={x} type="CENTRE OF EXCELLENCE"/>)}</div>:<><SectionHeading title="Partnerships for impact"/><p className="lead-copy">Explore KSLI’s Centres of Excellence and our partner network.</p><div className="cards-2 plain-cards"><Link to="/coe-partners/centres-of-excellence">Centres of Excellence →</Link><Link to="/coe-partners/our-partners">Our Partners →</Link></div></>}</section></>}
function OurPartners(){return <><PageIntro eyebrow="Collaboration" title="Our Partners">Collaborating with industry leaders and academic institutions to drive sustainable innovation and livelihood development.</PageIntro><section className="section shell"><LogoGrid title="Industrial Partners"/><div className="partner-spacer"/><LogoGrid title="Academic Partners"/></section></>}
function Submit(){return <><PageIntro eyebrow="Collaborate with KSLI" title="Submit Your Project">Share a project idea with the institute. This form is visual only in the current phase.</PageIntro><section className="section shell"><form className="form-card"><label>Project title<input placeholder="Enter a project title"/></label><label>Short description<textarea placeholder="Describe the project" rows="5"/></label><div className="form-grid"><label>Domain<select><option>Select domain</option><option>Sustainability</option><option>Livelihood</option></select></label><label>Category<select><option>Select category</option></select></label></div><label>Supporting images <input type="file" multiple/></label><button className="primary" type="button">Submit project</button></form></section></>}
function Contact(){return <><PageIntro eyebrow="Get in touch" title="Contact KSLI">Send an enquiry and the appropriate team will respond.</PageIntro><section className="section shell contact-grid"><form className="form-card"><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>Message<textarea rows="6" placeholder="How can we help?"/></label><button className="primary" type="button">Send enquiry</button></form><div><div className="contact-details"><h2>Visit or connect</h2><p>Address details to be confirmed.</p><p>Phone: Contact details to be confirmed.</p><p>Email: Contact details to be confirmed.</p></div><div className="map-placeholder">Map location placeholder</div></div></section></>}
function PageIntro({eyebrow,title,children}){return <><header className="page-intro"><div className="shell"><p className="eyebrow teal">{eyebrow}</p><h1>{title}</h1>{children&&<p>{children}</p>}</div></header>{title==='Our Partners'&&<section className="section shell"><LogoGrid title="Industrial Partners"/><div className="partner-spacer"/><LogoGrid title="Academic Partners"/></section>}</>}
function NotFound(){return <PageIntro title="Page not found">The requested route does not exist.</PageIntro>}
function App(){return <BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/sustainability" element={<DomainOverview domain="Sustainability"/>}/><Route path="/sustainability/microcosm" element={<Microcosm/>}/><Route path="/sustainability/research" element={<Listing kind="Research"/>}/><Route path="/sustainability/projects" element={<Listing kind="Projects"/>}/><Route path="/sustainability/events" element={<Listing kind="Events"/>}/><Route path="/livelihood" element={<DomainOverview domain="Livelihood"/>}/><Route path="/livelihood/research" element={<Listing domain="Livelihood" kind="Research"/>}/><Route path="/livelihood/projects" element={<Listing domain="Livelihood" kind="Projects"/>}/><Route path="/livelihood/events" element={<Listing domain="Livelihood" kind="Events"/>}/><Route path="/academic-programs" element={<AcademicOverview/>}/><Route path="/academic-programs/degrees" element={<Programs type="degrees"/>}/><Route path="/academic-programs/pathway" element={<Programs type="pathway"/>}/><Route path="/academic-programs/prototyping" element={<Programs type="prototyping"/>}/><Route path="/academic-programs/certificates" element={<Programs type="certificates"/>}/><Route path="/coe-partners" element={<Partners/>}/><Route path="/coe-partners/centres-of-excellence" element={<Partners centres/>}/><Route path="/coe-partners/our-partners" element={<PageIntro title="Our Partners">Collaborating with industry leaders and academic institutions.</PageIntro>}/><Route path="/about" element={<AboutKSLI/>}/><Route path="/submit-a-project" element={<Submit/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></Layout></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
